name: Docker Image CI

on:
  push:
  pull_request:
  schedules:
    - cron: '00 10 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build nodedev
      run: bash container/create.sh
    - name: build
      run: bash server/start_update.sh
    - name: Store inidence data
      uses: actions/upload-artifact@v2
      with:
        name: incidenceData
        path: node_build/incidenceData.json
