name: Docker Image CI

#on:
#  schedule:
#    - cron: "0 * * * *"
#  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build container
      run: bash container/python/create.sh
    - name: build
      run: bash server/start_update.sh
